[MCUX-72490][RW61X] Fix ota_examples build error
[Description]
undefined reference to `wlan_fw_bin'
undefined reference to `wlan_fw_bin_len'

[Root Cause]
Macros is app_config.h should be configurable from Kconfig

[Fix]
Replace app_config.h with Kconfig marco

[Testing]
Build Pass

Signed-off-by: Gang Li <gang.li_1@nxp.com>