[MCUX-72490] Fix compilation error for wifi_cli app
[Description]
Below compilation error is seen on wifi_cli app for various boards:
"fatal error: app_config.h: No such file or directory"

[Root Cause]
Issue was seen because of recent app_config.h to Kconfig changes. Few low end
boards were using different wifi_config.h than the one present under
middleware/wifi_nxp folder. These files still contain app_config.h include in
them which was causing this error.

[Fix]
Removed app_config.h include from wifi_confg.h file for low end boards.

[Testing]
Compilation success.

Signed-off-by: Sanjay Yadav <sanjay.yadav@nxp.com>