[WSW-71355][RW612][NCP] Fix server connection error
[Description]
Error: connect to server failed!

[Root Cause]
Failed to create socket

[Fix]
Handle socket creation errors and avoid using invalid sockets

[Testing]
NA

[Reviewers]
Gannicus Guo, Li Long, Hui Bai, Xinyu Hong, Gaofeng Zhang, Rex Chen

Signed-off-by: Gang Li <gang.li_1@nxp.com>