[MCUX-77221]Fix uart_wifi_bridge of FRDM-MCXN947 build errors.
[Description]
build error:
../source/wifi_bt_config.c:49:23: error: 'BOARD_INITPINSWIFI_SDIO_RST_GPIO' undeclared (first use in this function); did you mean 'BOARD_INITPINSWIFI_WL_RST_GPIO'?

[Root Cause]
BOARD_INITPINSWIFI_SDIO_RST_GPIO is defined in wifi_examples/common/pin_mux.h
File pin_mux.h used by uart_wifi_bridge is wifi_examples/uart_wifi_bridge/cm33_core0

[Fix]
Change wifi_bt_config.c as ${board_root}/${board}/wifi_bt_config.c

[Testing]
Success to build uart_wifi_bridge.

[Reviewers]
Gannicus Guo

Signed-off-by: Qiankun Li <qiankun.li@nxp.com>