[MCUX-88941][RW612][COEX] Fix missing edgefast_open_app.h
[Description]
fatal error: edgefast_open_app.h: No such file or directory

[Root Cause]
Not add to zippack

[Fix]
Add edgefast_open_app.h to zippack

[Testing]
N/A

[Reviewers]
Gannicus Guo, Hui Bai, Qiankun Li

Signed-off-by: Gang Li <gang.li_1@nxp.com>