[MCUX-84143]Fix build warnings caused by settings in the configuration file.
[Description]
There are build warnings:

mcuxsdk/examples/_boards/evkxxx/wifi_bt_config.c:16:2: error: "M.2 interface is not supported on this board" [-Werror,-W#warnings]

[Fix]
Now, can success to build MURATA_2LL_M2 wifi_xxx of evkxxx.
Remove the build warning prompts in wifi_bt_config.h

[Reviewers]
Gannicus Guo, Pankaj Razdan

Signed-off-by: Qiankun Li <qiankun.li@nxp.com>