[WSW-63465][NCP] Fix no load execution region
[Description]
Error: L6384E: No Load Execution Region of name RW_m_data2 seen yet at line 83.

[Root Cause]
no load execution region

[Fix]
Set EMPTY flag

[Testing]
NA

[Reviewers]
Gannicus Guo

Signed-off-by: Gang Li <gang.li_1@nxp.com>