[MCUX-80323] Fix coex_wifi_edgefast build error on IW610 evkbmimxrt1170 with armgcc 14.2.1
[Description]
coex_wifi_edgefast build error on IW610 evkbmimxrt1170 with armgcc 14.2.1
mcuxsdk/middleware/wireless/coex/build/evkbmimxrt1170/common/hardware_init.c:50:5: error:
implicit declaration of function 'BOARD_InitM2UARTPins'; did you mean 'BOARD_InitEnetPins'? [-Wimplicit-function-declaration]

[Root Cause]
coex_wifi_edgefast on evkbmimxrt1170 included pin_mux.h under '${board_root}/${board}/coex_examples/coex_wifi_edgefast/cm7'.
But the reconfig.cmake of coex_wifi_edgefast on evkbmimxrt1170 included extra wrong dir '${board_root}/${board}/wifi_examples/common' which contains pin_mux.h too.
So cause this build error

[Fix]
Remove the extra wrong dir '${board_root}/${board}/wifi_examples/common' from reconfig.cmake

[Testing]
Local build pass

Signed-off-by: Qingling Wu <qingling.wu@nxp.com>