[WSW-59614][RW612][WiFi][NCP] Fix memory leak
[Description]
Error: failed to allocate memory after run multi test cases

[Root Cause]
ncp_inet_recv_thread was not released.

[Fix]
Init ncp_inet_recv_thread once

[Testing]
Test pass on uart interface

[Reviewers]
Gannicus Guo

Signed-off-by: Gang Li <gang.li_1@nxp.com>